<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Zend Tool Web UI</title>
<link rel="stylesheet" type="text/css" href="webui.css" />
</head>
<body>
<fieldset>
<legend>Zend Tool</legend>
<?php if ($response->isException()): ?>
<p><?php echo $response->getException(); ?></p>
<?php endif; ?>
<form id="zendToolForm" name="zendToolForm" method="post" action="">
<h3>Path of Project</h3>
<div>
<label for="projectPath">Path</label><input type="text" name="projectPath" id="projectPath" value="<?php echo $projectPath; ?>" />
</div>
<h3>Function</h3>
<div>
<label for="provider">Provider</label>
<select name="provider" id="provider">
<option value="">Please Select...</option>
</select>
</div>
<div>
<label for="action">Action</label>
<select name="action" id="action">
<option value="Show">Please Select...</option>
</select>
</div>
<h3>Options</h3>
<div id="parameterInfo">
</div>
<div class="buttons">
<input type="submit" id="run" value="Execute" />
</div>
</form>
</fieldset>
<div id="toolInfo">
<h3>Result</h3>
<pre></pre>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="http://github.com/SamWM/jQuery-Plugins/raw/master/selectboxes/jquery.selectboxes.min.js"></script>
<script type="text/javascript" src="http://github.com/malsup/form/raw/master/jquery.form.js"></script>
<script type="text/javascript">
var providers = <?php echo json_encode(array_combine(array_keys($options), array_keys($options))); ?>;
var providerActions = <?php echo json_encode($options); ?>;
</script>
<script type="text/javascript" src="webui.js"></script>
</body>
</html>